v1 = input("Digite algo: ")
print ("O tipo primitivo desse valor é", type(v1))
print ("Só tem espaços? ", v1.isspace())
print ("É um número? ", v1.isnumeric())
print ("É alfabético? ", v1.isalpha())
